repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v1.2.3
  hooks:
  - id: check-ast
  - id: check-merge-conflict
  - id: check-executables-have-shebangs
  - id: check-symlinks
  - id: check-toml
  - id: check-yaml
  - id: detect-private-key
repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.8.5
  hooks:
  - id: ruff
    args: [ --fix ]
  - id: ruff-format
- repo: local
  hooks:
  - id: nix-fmt
    name: nix-fmt
    entry: "nix fmt"
    types: [nix]
    language: system
